### ISSUE TITLE
nexusrules.officeapps.live.com, false positive on whitelist

### ISSUE THREAD

**Issue by RichardBeisser** [fabriziosalmi/blacklists#113]
Hello

regarding
nexusrules.officeapps.live.com
vortex.data.microsoft.com
web.vortex.data.microsoft.com

--> https://learn.microsoft.com/en-us/microsoft-365/enterprise/network-requests-in-office-2016-for-mac?view=o365-worldwide
--> https://learn.microsoft.com/en-us/visualstudio/install/install-and-use-visual-studio-behind-a-firewall-or-proxy-server?view=vs-2022#urls-to-add-to-an-allowlist-and-ports-and-protocols-to-open

I think telemetry is nothing what should be on a whitelist. I would suggest that people add these domain by themselves if they really need it.
Please check

**Comment by fabriziosalmi** [comment]
checking, I'll keep you posted here, really appreciated.

**Comment by fabriziosalmi** [comment]
removed, thank you ;-)
