### ISSUE TITLE
clientstream.launchdarkly.com, false positive in whitelist

### ISSUE THREAD

**Issue by RichardBeisser** [fabriziosalmi/blacklists#115]
Hello,

just discovered 
clientstream.launchdarkly.com
in whitelist.

--> https://www.devstringx.com/launch-darkly
I think this is nothing which should be in a whitelist which is used in a wide area like your one.
A app should be stable when it is installed.

I go confirm that is is blocked 
https://raw.githubusercontent.com/ftpmorph/ftpihole/master/blocklists/smartphone-ads-tracking.txt

**Comment by fabriziosalmi** [comment]
removed
