### ISSUE TITLE
DoH blocklist

### ISSUE THREAD

**Issue by Microices** [fabriziosalmi/blacklists#116]
Unsure if it would be possible to add DoH servers to the list or if the current list covers doh servers as well.

**Comment by fabriziosalmi** [comment]
DOH servers not in scope but can be discussed of course :) U welcome

**Comment by fabriziosalmi** [comment]
Best candidate seems to be https://github.com/dibdot/DoH-IP-blocklists/blob/master/doh-domains.txt

**Comment by Microices** [comment]
I am using this however it has not been updated for sometime. [https://github.com/oneoffdallas/dohservers/tree/master]

**Comment by KnightmareVIIVIIXC** [comment]
What about this: https://github.com/hagezi/dns-blocklists#outbox_tray-encrypted-dns-servers-only-

**Comment by fabriziosalmi** [comment]
this one will be included after a quick review: https://cdn.jsdelivr.net/gh/hagezi/dns-blocklists@latest/adblock/doh.txt

**Comment by fabriziosalmi** [comment]
I was thinking to reopen this discussion since DOH is taking places..

**Comment by fabriziosalmi** [comment]
Best candidate: https://github.com/dibdot/DoH-IP-blocklists/blob/master/doh-domains.txt
