### ISSUE TITLE
c.amazon-adsystem.com in whitelist.txt

### ISSUE THREAD

**Issue by RichardBeisser** [fabriziosalmi/blacklists#118]
Hello,

c.amazon-adsystem.com is in whitelist.

This can only be a mistake.

**Comment by fabriziosalmi** [comment]
Thank You to point me out to this crap, instantly removed.

**Comment by RichardBeisser** [comment]
Thanks.

Just for interest, where so you get the entries for whitelist from?

**Comment by fabriziosalmi** [comment]
>Thanks. ...

@RichardBeisser daily home use and mobile use then it’s biased. also manually added from github sources time after time 

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>
