### ISSUE TITLE
analytics.furka-europe.com and analytics.hypmed.de should be added whitelist

### ISSUE THREAD

**Issue by HydraDragonAntivirus** [fabriziosalmi/blacklists#120]
Also you can use my database at xylent.sourceforge.io

**Comment by fabriziosalmi** [comment]
db for whitelisting items u mean?

**Comment by HydraDragonAntivirus** [comment]
https://sourceforge.net/p/xylent/git/ci/master/tree/backend/website/ here is the whitelist and my signatures.
