### ISSUE TITLE
Source suggestion 

### ISSUE THREAD

**Issue by jarelllama** [fabriziosalmi/blacklists#121]
Hi, I'm the maintainer of https://github.com/jarelllama/Scam-Blocklist , a blocklist for newly created scam domains automatically retrieved daily using Google Search API, automated detection, and other public sources.

Seems like a good fit if you're willing to add it as a source.

Note that my list is already included in Hagezi's TIF list and the light version of my list in his TIF Medium list. But his list updates at 04:00 UTC whereas mine at 10:00 UTC.

**Comment by fabriziosalmi** [comment]
I'll add the larger one, really appreciated! ❤️

**Comment by jarelllama** [comment]
Cheers!

**Comment by fabriziosalmi** [comment]
u welcome! (https://github.com/fabriziosalmi/blacklists/commit/e80570a9b44816d91e5b3909b6e9302ca49358b9)
