### ISSUE TITLE
overlapping in the blocklist sources (Same sources repeated)

### ISSUE THREAD

**Issue by AyanokojiK1yotaka** [fabriziosalmi/blacklists#122]
there are many overlap in the blocklist sources

https://o0.pages.dev/Pro/domains.txt
https://o0.pages.dev/mini/domains.txt

1hosts pro already contains everything in 1hosts mini and more(1hosts mini can be removed)

https://raw.githubusercontent.com/badmojr/1Hosts/master/Lite/domains.txt
https://raw.githubusercontent.com/badmojr/1Hosts/master/Pro/domains.txt
https://raw.githubusercontent.com/badmojr/1Hosts/master/mini/domains.txt

all of this can be removed as they are repeated

This is https://raw.githubusercontent.com/hagezi/dns-blocklists/main/adblock/personal.txt
already included in https://raw.githubusercontent.com/hagezi/dns-blocklists/main/domains/ultimate.txt.So it can be removed.

https://www.github.developerdan.com/hosts/lists/tracking-aggressive-extended.txt
https://raw.githubusercontent.com/lightswitch05/hosts/master/docs/lists/tracking-aggressive-extended.txt
They are the same.

So totally this are the lists which should be removed as they are repeated unnecessarily  :

https://o0.pages.dev/mini/domains.txt
https://raw.githubusercontent.com/badmojr/1Hosts/master/Lite/domains.txt
https://raw.githubusercontent.com/badmojr/1Hosts/master/Pro/domains.txt
https://raw.githubusercontent.com/badmojr/1Hosts/master/mini/domains.txt
https://raw.githubusercontent.com/hagezi/dns-blocklists/main/adblock/personal.txt
https://raw.githubusercontent.com/lightswitch05/hosts/master/docs/lists/tracking-aggressive-extended.txt

**Comment by HydraDragonAntivirus** [comment]
Also there duplicates and yandex domains are false positive

**Comment by fabriziosalmi** [comment]
checking blacklist and whitelist clean up code, thank you buddies 👍

**Comment by fabriziosalmi** [comment]
@AyanokojiK1yotaka really appreciated, checked and removed!! Lighter is better ❤️
