### ISSUE TITLE
Raw file

### ISSUE THREAD

**Issue by christianbj87** [fabriziosalmi/blacklists#138]
Hello, excellent work.
Could you upload the blacklist.txt file to the repo so it can be downloaded as raw please?
In my case, with the security service I have, I can't sync it to txt because it is not as raw.
Like: https://raw.githubusercontent.com/<youruser>/.../master/blacklist.txt

Thank you!

**Comment by fabriziosalmi** [comment]
Helo, thank you for kind words :) The release file is a raw txt downloadable from the GitHub CDN powered by Fastly: 
https://github.com/fabriziosalmi/blacklists/releases/download/latest/blacklist.txt

**Comment by fabriziosalmi** [comment]
what if u point to https://get.domainsblacklists.com/blacklist.txt ?

**Comment by fabriziosalmi** [comment]
another way to achieve this mission can be to push the updated blacklist to some cloudflare page and have an additional waw url outside the repo.. i'll check that way

**Comment by christianbj87** [comment]
Hi Fabrizio, thank you for your reply.
My FW solution needs the file to be read from the web browser. For that reason I suggested the idea of uploading it to the repo and being able to fetch it from raw.githubusercontent.com/..../blacklist.txt

Example of an ip list in raw: https://raw.githubusercontent.com/stamparm/ipsum/master/levels/2.txt
Another example:
https://www.spamhaus.org/drop/drop.txt
These are limitations of my vendor, in case it can't be adapted there is no problem anyway, I thank you for your work.
Thanks for your help Fabrizio
 regards.

**Comment by fabriziosalmi** [comment]
U got it: https://fabriziosalmi.github.io/blacklists/blacklist.txt

**Comment by christianbj87** [comment]
Thank you for your help Fabrizio.
 The last file you send me does not contain the same amount of domains, maybe it is an old version?
Last-Modified: | Wed, 13 Sep 2023

Is there a possibility that it is kept up to date as the main blacklist.txt file?

Regards!

**Comment by fabriziosalmi** [comment]
Yes I need to fix the pipeline maybe, TY to point me out to that I will try to achieve the mission before tomorrow :)
