### ISSUE TITLE
not found

### ISSUE THREAD

**Issue by alsyundawy** [fabriziosalmi/blacklists#142]
Squid: [blacklist.txt](https://github.com/fabriziosalmi/blacklists/releases/download/latest/blacklist.txt)
Unbound: [unbound_blacklist.txt](https://github.com/fabriziosalmi/blacklists/releases/download/latest/unbound_blacklist.txt)
Bind, PowerDNS (RPZ): [rpz_blacklist.txt](https://github.com/fabriziosalmi/blacklists/releases/download/latest/rpz_blacklist.txt)

**Comment by fabriziosalmi** [comment]
Temporary failure
